### ISSUE TITLE
Is it possible to have support for Spark streaming ?

### ISSUE THREAD

**Issue by SundeepMehta** [zhengruifeng/SparkGBM#1]
Hey,
Is it possible to have support for Spark streaming similar to online algorithm like StreamingLogisticRegressionWithSGD ?
 I am already using StreamingLogisticRegressionWithSGD for CTR prediction and was looking to try out your Spark GBM implementation for feature importance. 

Regards
Sundeep

**Comment by zhengruifeng** [comment]
Sorry to reply so late.
If you mean online training algorithm like FTRL, I am not sure whether it is doable or effective to implement a online-training GBM, although there are some papers.
For decision tree, Hoeffding Tree supoort online training and was implemented in MOA(https://moa.cms.waikato.ac.nz/details/).

**Comment by SundeepMehta** [comment]
thanks a lot, I will take a look at Hoeffding Tree.

Regards
Sundeep
